{{- range $namespace := .Values.deployments }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ $namespace.name }}
  labels:
    app.kubernetes.io/name: {{ $namespace.name }}
    {{- include "deployment.labels" $ | nindent 4 }}
spec:
  strategy:
    type: {{ $namespace.strategy.type }}
    rollingUpdate:
      maxSurge: {{$namespace.strategy.maxSurge}}
      maxUnavailable: {{$namespace.strategy.maxUnavailable}}
  {{- if not $namespace.autoscaling.enabled }}
  replicas: {{ $namespace.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ $namespace.name }}
      {{- include "deployment.selectorLabels" $ | nindent 6 }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ $namespace.name }}
        {{- include "deployment.selectorLabels" $ | nindent 8 }}
    spec:
      {{- with $namespace.volumes }}
      volumes:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with $.Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "deployment.serviceAccountName" $ }}
      containers:
        - name: {{ $namespace.name }}
          image: "{{ $.Values.image.repository }}:{{ $.Values.image.tag }}"
          imagePullPolicy: {{ $.Values.image.pullPolicy }}
          {{- with $namespace.livenessProbeEnabled }}
          livenessProbe:
            failureThreshold: 3
            httpGet:
              path: {{ $namespace.livenessProbe.healthCheckPath }}
              port: {{ $namespace.containerPort }}
              scheme: HTTP
            periodSeconds: 30
            successThreshold: 1
            timeoutSeconds: 30
            initialDelaySeconds: 60
          readinessProbe:
            failureThreshold: 3
            httpGet:
              path: {{ $namespace.livenessProbe.healthCheckPath }}
              port: {{ $namespace.containerPort }}
              scheme: HTTP
            periodSeconds: 30
            successThreshold: 1
            timeoutSeconds: 30
            initialDelaySeconds: 60
          {{- end }}
          {{- with $namespace.volumeMounts }}
          volumeMounts:
            {{- toYaml . | indent 10 }}
          {{- end}}
          {{- with $namespace.containerPortEnabled }}
          ports:
            - containerPort: {{ $namespace.containerPort }}
          {{- end }}
          envFrom:
            {{- range $k := $namespace.secretsRef }}
            - secretRef:
                name: {{ $k }}
            {{- end }}
          resources:
            {{- toYaml $namespace.resources | nindent 12 }} 
          command: 
          {{- range $k := $namespace.command }}
            - {{ $k }}
          {{- end }}
      {{- with $namespace.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
---
{{- end }}
