{{- if .Values.hpa }}{{ if .Values.hpa.enabled -}}
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: {{ include "app.fullname" . }}
  labels:
    {{- include "app.labels" . | nindent 4 }}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ include "app.fullname" . }}
  minReplicas: {{ .Values.deployment.api.autoscaling.minReplicas }}
  maxReplicas: {{ .Values.deployment.api.autoscaling.maxReplicas }}
  metrics:
    {{- if .Values.deployment.api.autoscaling.targetCPUUtilizationPercentage }}
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: {{ .Values.deployment.api.autoscaling.targetCPUUtilizationPercentage }}
    {{- end }}
    {{- if .Values.deployment.api.autoscaling.targetMemoryUtilizationPercentage }}
    - type: Resource
      resource:
        name: memory
        target:
          type: AverageValue
          averageValue: {{ .Values.deployment.api.autoscaling.targetMemoryUtilizationPercentage }}
    {{- end }}
{{- end }}{{ end }}
