{{- range $job := .Values.jobs }}
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ $job.name }}
  labels:
    app.kubernetes.io/name: {{ $job.name }}
    {{- include "deployment.labels" $ | nindent 4 }}
  annotations:
    {{- range $key, $value := $job.annotations }}
    {{- printf "%s: %s" $key (tpl $value $ | quote) | nindent 4 }}
    {{- end }}
spec:
  template:
    metadata:
      name: {{ $job.name }}
    spec:
      restartPolicy: Never
      containers:
      - name: {{ $job.name }}
        image: "{{ $.Values.image.repository }}:{{ $.Values.image.tag }}"
        envFrom:
            {{- range $k := $job.secretsRef }}
            - secretRef:
                name: {{ $k }}
            {{- end }}
        command:
        {{- range $k := $job.command }}
          - {{ $k }}
        {{- end }}
---
{{ end }}