---
replicaCount: 1

environmentVariables: {}

nameOverride: fabconnect

fullnameOverride: fabconnect

externalSecrets: {}
  

serviceAccount: {}

nodeSelector:
  eks.amazonaws.com/nodegroup: fabric

aws:
  region: us-west-2

image: {}

services:
  service1:
    name: fabconnect
    type: NodePort
    protocol: TCP
    servicePort: 5102
    servicePortName: fabconnect
    containerPort: 5102

ingresses: {}

deployments:
  deployment1:
    name: fabconnect
    strategy:
      type: RollingUpdate
      maxSurge: 1
      maxUnavailable: 50%
    autoscaling:
      enabled: false
    containerPortEnabled: true
    containerPort: 5102
    livenessProbeEnabled: true
    livenessProbe:
      healthCheckPath: /status
    nodeSelector:
      eks.amazonaws.com/nodegroup: fabric
    resources:
      limits:
        cpu: 1000m
        memory: 1Gi
      requests:
        cpu: 200m
        memory: 256Mi
    replicaCount: 1
    secretsRef:
      - "fabconnect"
    command: [./fabconnect, -f, /fabconnect/config.yaml]
    volumeMounts:
      - name: fabconnect
        readOnly: true
        mountPath: /fabconnect/config.yaml
        subPath: config.yaml
      - name: fabconnect
        readOnly: true
        mountPath: /fabconnect/ccp.yaml
        subPath: ccp.yaml
      - name: receipts-pvc
        mountPath: /fabconnect/receipts
      - name: events-pvc
        mountPath: /fabconnect/events  
      - name: firefly-msp
        mountPath: /etc/firefly/msp
      - name: vault-ca
        mountPath: /etc/ssl/certs/vault.ca
        subPath: vault.ca
    volumes:
      - name: fabconnect
        configMap:
          name: fabconnect
          defaultMode: 420
      - name: receipts-pvc
        persistentVolumeClaim:
          claimName: fabconnect-receipts
      - name: events-pvc
        persistentVolumeClaim:
          claimName: fabconnect-events
      - name: firefly-msp
        emptyDir: {}
      - name: vault-ca
        configMap:
          name: vault-ca.root
          defaultMode: 420

persistentVolumes:
  pvc1:
    name: fabconnect-receipts
    storage: 50Gi
    volumeID: vol-fab-receipts-123
    namespace: fabric
    claim:
      labels: {}
      annotations: {}
    volume:
      labels: {}
      annotations: {}
  pvc2:
    name: fabconnect-events
    storage: 50Gi
    volumeID: vol-fab-events-123
    namespace: fabric
    claim:
      labels: {}
      annotations: {}
    volume:
      labels: {}
      annotations: {}